-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users Table (Public Profile)
create table if not exists public.users (
    id uuid references auth.users(id) on delete cascade primary key,
    email text,
    full_name text,
    role text default 'citizen',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Reports Table
create table if not exists public.reports (
    id uuid default uuid_generate_v4() primary key,
    user_id text not null,
    latitude float not null,
    longitude float not null,
    description text not null,
    severity int not null,
    ai_class text,
    ai_confidence float,
    status text default 'pending',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    blockchain_tx text,
    location text
);

-- Photos Table
create table if not exists public.photos (
    id uuid default uuid_generate_v4() primary key,
    report_id uuid references public.reports(id) on delete cascade,
    url text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Blockchain Logs Table
create table if not exists public.blockchain_logs (
    id uuid default uuid_generate_v4() primary key,
    report_id uuid references public.reports(id) on delete cascade,
    tx_hash text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Water Quality Readings Table
create table if not exists public.water_quality_readings (
    id bigint generated by default as identity primary key,
    location text not null,
    latitude float,
    longitude float,
    ph float,
    turbidity float,
    oxygen float,
    salinity float,
    temperature float,
    recorded_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Success Stories Table
create table if not exists public.success_stories (
    id bigint generated by default as identity primary key,
    title text not null,
    location text not null,
    timeframe text,
    description text,
    image_url text,
    status text,
    water_quality_improved float,
    species_recovered int,
    lives_impacted int,
    pollution_reduced float,
    challenges text,
    solutions text,
    results text,
    stakeholders text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Storage Bucket for Photos
-- Note: You need to create the 'photos' bucket in the Storage section of Supabase dashboard manually if it doesn't exist.
-- And set the policy to allow public read and authenticated upload.
